"""empty message

Revision ID: 4b13cc59af44
Revises: 427ff7c411e3
Create Date: 2024-10-20 02:47:15.612685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4b13cc59af44'
down_revision: Union[str, None] = '427ff7c411e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_organisation')
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('created',
               existing_type=sa.NUMERIC(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organisation', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.NUMERIC(),
               nullable=True)
        batch_op.drop_column('seed')

    op.create_table('_alembic_tmp_organisation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('encoded_wallet', sa.VARCHAR(), nullable=False),
    sa.Column('created', sa.NUMERIC(), nullable=False),
    sa.Column('updated', sa.NUMERIC(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
